### ISSUE TITLE
moveForward crashes server

### ISSUE THREAD

**Issue by Kneesnap** [InventivetalentDev/CompactNPCLib#13] opened 2016-08-01 01:27 UTC
## What steps will reproduce the problem?
1.  Create an NPCPlayer
2.  Run #moveForward(3.0F, 1.0F);
## What were you expecting to happen? What happened instead?

I expected the entity to move forward, instead the entire server crashed
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

Version 2.2.1
## What Spigot version are you using? _Type /version_

This server is running Paper version git-Paper-808 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
## What plugins are you using? _Type /plugins_

Plugins (4): PacketListenerApi, NickNamer, NPCLib, GravelSlash
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

http://pastebin.com/ix0AKTHX
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No

**Comment by InventivetalentDev** [comment] 2016-08-01 09:20
Can you please try the same plugin on a default Spigot server? I'll guess this is caused by PaperSpigot.

**Comment by annoyingcalc** [comment] 2016-08-02 02:37
Confirmed on Spigot 1.10.2.

This server is running CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

Here's the class, for reference

public class AISneakLookout extends AICustom{
	
	private boolean lookDir;
	
	public AISneakLookout (NPCPlayer player) {
		super(player);
		this.getPlayer().setSneaking(true);
		this.setYaw(180);
	}
	
	@Override
	public void tick(){
		super.tick();
		this.getNpc().moveForward(0.5F, 0.1F);
		if(!this.hasTimePassed(2000)){
			return;
		}
		this.lookDir = !this.lookDir;
		if(this.lookDir){
			this.setYaw(135);
		}else{
			this.setYaw(-135);
		}
	}
}

**Comment by InventivetalentDev** [comment] 2016-08-02 08:47
Should be fixed in v2.2.2.

**Closed** 2017-02-02 15:11 UTC
